# Generated by Django 3.2.16 on 2022-12-26 02:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('states', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('document', models.CharField(max_length=30, unique=True)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('image', models.ImageField(null=True, upload_to='users')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('coordinates_lat', models.CharField(blank=True, max_length=100, null=True)),
                ('coordinates_len', models.CharField(blank=True, max_length=100, null=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.documenttype')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.state')),
            ],
        ),
        migrations.CreateModel(
            name='Type_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('polling_station', models.IntegerField()),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.documenttype')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.leader')),
                ('polling_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.pollingplace')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.state')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_changed', models.DateTimeField(auto_now_add=True)),
                ('data', models.CharField(blank=True, max_length=500, null=True)),
                ('type_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.type_log')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.voter')),
            ],
        ),
    ]
