# Generated by Django 3.2.16 on 2022-12-26 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221225_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='full_name',
        ),
    ]
