# Generated by Django 3.2.16 on 2022-12-26 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_leader_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='state',
        ),
    ]
