# Generated by Django 3.2.16 on 2022-12-26 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_leader_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='leader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.leader'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leader',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leader',
            name='coordinates_lat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leader',
            name='coordinates_len',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='log',
            name='data',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
