# Generated by Django 3.2.16 on 2022-12-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingplace',
            name='coordinates_lat',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pollingplace',
            name='coordinates_len',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pollingplace',
            name='n_polling_station',
            field=models.IntegerField(),
        ),
    ]
