# Generated by Django 3.2.16 on 2022-12-26 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
        ('locations', '0004_alter_city_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.state'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.state'),
        ),
        migrations.AlterField(
            model_name='pollingplace',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.state'),
        ),
    ]
