# Generated by Django 3.2.16 on 2022-12-26 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
        ('locations', '0005_auto_20221225_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='states.state'),
        ),
        migrations.AlterField(
            model_name='department',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='states.state'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='states.state'),
        ),
        migrations.AlterField(
            model_name='pollingplace',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='states.state'),
        ),
    ]
