# Generated by Django 3.2.16 on 2022-12-26 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_alter_city_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
    ]
