# Generated by Django 3.2.16 on 2022-12-26 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_remove_city_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='state',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='state',
        ),
        migrations.RemoveField(
            model_name='pollingplace',
            name='state',
        ),
    ]
